---
  - name: Tasks to create air-gapped vault
    block:
      - name: Set endpoint, http method and request payload
        ansible.builtin.set_fact:
          api_http_method: "PUT"
          api_service: "backup"
          api_host: "backup.{{ aws_region }}.amazonaws.com"
          api_endpoint: "/logically-air-gapped-backup-vaults/{{ vault_name }}"
          request_payload: "{{ create_vault_request | to_json }}"
        no_log: true

      - name: Call aws_api_credentials Role to get credentials for api request
        ansible.builtin.include_role:
          name: aws_api_credentials
#          vars:
#            api_http_method: "{{ api_http_method }}"
#            api_service: "{{ api_service }}"
#            api_host: "{{ api_host }}"
#            api_endpoint: "{{ api_endpoint }}"
#            request_payload: "{{ request_payload }}"

      - name: Create logically air-gapped Backup Vault
        ansible.builtin.uri:
          url: "{{ aws_backup_base_url }}{{ api_endpoint }}"
          method: "{{ api_http_method }}"
          headers:
            host: "{{ api_host }}"
            x-amz-date: "{{ x_amz_date }}"
            x-amz-security-token: "{{ x_amz_security_token }}"
            Authorization: "{{ Authorization }}"
          body: "{{ request_payload }}"
          force_basic_auth: false
          status_code: 200
          body_format: json
          use_proxy: false
          validate_certs: false
          return_content: true
        environment:
          AWS_SESSION_TOKEN: "{{ aws_api_session_token }}"
          AWS_ACCESS_KEY_ID: "{{ aws_api_access_key_id }}"
          AWS_SECRET_ACCESS_KEY: "{{ aws_api_secret_access_key }}"
        register: vault_creation_response
        delegate_to: localhost

      - name: Set vault info variable
        ansible.builtin.set_fact:
          vault_info: "{{ vault_creation_response.content | from_json }}"

      - name: Set the ARN (Amazon Resource Name) of the vault
        ansible.builtin.set_fact:
          vault_arn: "{{ vault_info.BackupVaultArn }}"

      - name: Set values to pass to workflow
        ansible.builtin.set_stats:
          data:
            backup_vault_arn: "{{ vault_arn }}"
    rescue:
      - name: Log failure message
        ansible.builtin.debug:
          msg: "Task {{ ansible_failed_task.name }} failed with the following message {{ ansible_failed_result.stderr }}"

