---
vault_network_isolation_enabled: false
vault_vpc_cidr: 10.42.0.0/16
vault_az_count: 2
vault_single_nat_gateway: true
vault_subnet_public_cidrs:
  - 10.42.0.0/24
  - 10.42.1.0/24
vault_subnet_egress_cidrs:
  - 10.42.10.0/24
  - 10.42.11.0/24
vault_subnet_ingress_cidrs:
  - 10.42.20.0/24
  - 10.42.21.0/24
vault_vpc_name: sh-vault-isolation
vault_provision_vgw: true
vault_vpc_interface_endpoints_enabled: true
