---
backup_plan_name: TestBackupPlanAutomated
backup_rule_name: Daily-Rule
backup_rule_schedule: cron(0 5 * * ? *)
backup_cold_storage_days: 30
backup_delete_after_days: 120
backup_iam_role: arn:aws:iam::123456789012:role/service-role/AWSBackupDefaultServiceRole