---
backup_plan_name: TestBackupPlanAutomated
backup_rule_name: Daily-Rule
backup_resource_name: Demo_Resource
backup_rule_schedule: cron(0 5 * * ? *)
backup_cold_storage_days: 30
backup_delete_after_days: 30
backup_iam_role: arn:aws:iam::961341512032:role/service-role/AWSBackupDefaultServiceRole
secondary_backup_vault_arn: placeholder